server:
  port: 8090

spring:
  application:
    name: citnow-line-integration

line.bot:
  channelToken: ${LINECORP_PLATFORM_CHANNEL_CHANNELTOKEN}
  channelSecret: ${LINECORP_PLATFORM_CHANNEL_CHANNELSECRET}
  handler.path: ${LINECORP_PLATFORM_CHANNEL_CALLBACKURL}
